name:               "FireG"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "thinker3197"
email:              "1216999604@qq.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "https://github.com/FireG"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "关于"
    href:           "/about"
  - name:           "下载"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate